# Generated by Django 5.0.1 on 2025-06-02 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rule',
            options={},
        ),
        migrations.RemoveField(
            model_name='rule',
            name='content',
        ),
        migrations.RemoveField(
            model_name='rule',
            name='order',
        ),
        migrations.AddField(
            model_name='rule',
            name='description',
            field=models.TextField(default='Rule description'),
        ),
        migrations.AddField(
            model_name='rule',
            name='title',
            field=models.CharField(default='Game Rule', max_length=200),
        ),
    ]
